name: Docker Build & Push to AWS ECR (Dynamic Microservices)

on:
  push:
    branches:
      - main
    paths:
      - 'microservices/product-service/**'
      - 'microservices/cart-service/**'
      - 'microservices/order-service/**'
      - 'microservices/inventory-service/**'
      - 'microservices/payment-service/**'
      - 'microservices/user-auth-service/**'
      - 'microservices/notification-service/**'
      - 'microservices/search-service/**'

jobs:
  build-and-push:
    name: Build & Push Updated Microservice
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Ensures previous commit is available for comparison

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
          role-session-name: GitHubActions
          aws-region: ${{ secrets.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Determine Which Microservice Changed
        id: determine-service
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          echo "Changed files: $CHANGED_FILES"

          if echo "$CHANGED_FILES" | grep -q "microservices/product-service/"; then
            echo "SERVICE_NAME=product-service" >> $GITHUB_ENV
          elif echo "$CHANGED_FILES" | grep -q "microservices/cart-service/"; then
            echo "SERVICE_NAME=cart-service" >> $GITHUB_ENV
          elif echo "$CHANGED_FILES" | grep -q "microservices/order-service/"; then
            echo "SERVICE_NAME=order-service" >> $GITHUB_ENV
          elif echo "$CHANGED_FILES" | grep -q "microservices/inventory-service/"; then
            echo "SERVICE_NAME=inventory-service" >> $GITHUB_ENV
          elif echo "$CHANGED_FILES" | grep -q "microservices/payment-service/"; then
            echo "SERVICE_NAME=payment-service" >> $GITHUB_ENV
          elif echo "$CHANGED_FILES" | grep -q "microservices/user-auth-service/"; then
            echo "SERVICE_NAME=user-auth-service" >> $GITHUB_ENV
          elif echo "$CHANGED_FILES" | grep -q "microservices/notification-service/"; then
            echo "SERVICE_NAME=notification-service" >> $GITHUB_ENV
          elif echo "$CHANGED_FILES" | grep -q "microservices/search-service/"; then
            echo "SERVICE_NAME=search-service" >> $GITHUB_ENV
          else
            echo "No microservice change detected. Skipping build."
            exit 0
          fi

      - name: Build, Tag, and Push Docker Image to AWS ECR
        run: |
          if [ -z "$SERVICE_NAME" ]; then
            echo "No relevant changes detected. Skipping build."
            exit 0
          fi

          echo "Building Docker image for $SERVICE_NAME..."
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ecomdev/$SERVICE_NAME:latest ./microservices/$SERVICE_NAME
          
          echo "Pushing Docker image to ECR..."
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ecomdev/$SERVICE_NAME:latest
